/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consulta;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import vista.inicio;
import vista.login;


public class Consulta1 extends javax.swing.JFrame {
    
    
    

    Tabla_ProductoVO t = new Tabla_ProductoVO();
    
    ProductoDAO dao;
    
    int clic_tabla = 0;
    
     PreparedStatement ps;
    ResultSet rs;
    Connection con = null;
    Statement stmt = null;
    String var,var2;
    
  
    
    public Consulta1() {
        initComponents();
        this.setExtendedState(6);
        t.visualizar_ProductoVO(tabla);  
        activa_boton(true,false,false);
    }

private void limpiarCajas(){
     txt_ID.setText(null);
     txt_nombre_usuario.setText(null);
     txt_contraseña.setText(null);
     txt_nombre.setText(null);
     txt_apellido.setText(null);
     txt_telefono.setText(null);
     txt_correo.setText(null);  
     
 }
    
    //Metodo eliminar producto
    public void modificar(){
        dao = new ProductoDAO();
        ProductoVO vo = new ProductoVO();
         vo.setID(txt_ID.getText());
        vo.setNombre_Usuario(txt_nombre_usuario.getText());
        vo.setContraseña(txt_contraseña.getText());
        vo.setNombre(txt_nombre.getText());
        vo.setApellido(txt_apellido.getText());
        vo.setTelefono(txt_telefono.getText());
        vo.setCorreo(txt_correo.getText());
       
        dao.Modificar_ProductoVO(vo);
        
    }
    
    
public void activa_boton(boolean a1, boolean a2, boolean a3){
        btnModificar.setEnabled(a2);
        btnEliminar.setEnabled(a2);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        txt_nombre_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnEliminar2 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD para Productos");
        setForeground(new java.awt.Color(255, 255, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 940, 230));

        panel.setBackground(new java.awt.Color(51, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 0, 18))); // NOI18N
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel3.setText("Telefono:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        panel.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 30));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        panel.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel1.setText("Nombre Usuario:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel2.setText("Nombre:");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel5.setText("Contraseña:");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel7.setText("Correo:");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        panel.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 160, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel10.setText("Apellido:");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        panel.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 30));

        txt_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_usuarioActionPerformed(evt);
            }
        });
        panel.add(txt_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 30));

        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });
        panel.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel4.setText("ID:");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        panel.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, 30));

        btnEliminar.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panel.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 40));

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panel.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 40));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 360, 490));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel11.setText("Consulta Usuario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        btnEliminar2.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnEliminar2.setText("Cerrar Ventana");
        btnEliminar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar2.setContentAreaFilled(false);
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 200, 40));

        btnEliminar1.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnEliminar1.setText("Volver al inicio");
        btnEliminar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar1.setContentAreaFilled(false);
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
        clic_tabla = this.tabla.rowAtPoint(evt.getPoint());
        String ID = ""+tabla.getValueAt(clic_tabla, 0);
        String Nombre_Usuario = ""+tabla.getValueAt(clic_tabla, 1);
        String Contraseña= ""+tabla.getValueAt(clic_tabla, 2);
        String Nombre = ""+tabla.getValueAt(clic_tabla, 3);
        String Apellido = ""+tabla.getValueAt(clic_tabla, 4);
        String Telefono = ""+tabla.getValueAt(clic_tabla, 5);
        String Correo = ""+tabla.getValueAt(clic_tabla, 6);
        
        txt_ID.setText(ID);
        txt_nombre_usuario.setText(Nombre_Usuario);
        txt_contraseña.setText(Contraseña);
        txt_nombre.setText(Nombre);
        txt_apellido.setText(Apellido);
        txt_telefono.setText(Telefono);
        txt_correo.setText(Correo);
        
        int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tabla.getRowHeight();
        
        if(row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0){
            Object value = tabla.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                
                if(boton.getName().equals("m")){
                    System.out.println("Click en el boton modificar");
                    //EVENTOS MODIFICAR
                    activa_boton(false,true,false);
                }
                if(boton.getName().equals("e")){
                    System.out.println("Click en el boton eliminar");
                    //EVENTOS eliminar
                    activa_boton(false,true,false);
                }
            }

        }
        
    }//GEN-LAST:event_tablaMouseClicked

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    limpiarCajas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
        t.visualizar_ProductoVO(tabla);
        activa_boton(true,false,false);
       limpiarCajas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int id = Integer.parseInt(txt_ID.getText()) ;
        int respuesta = JOptionPane.showConfirmDialog(null,"seguro que quieres eliminar a :"+ id);
        if(respuesta==JOptionPane.YES_OPTION){
           
            ProductoDAO.eliminar_reg(id);
        }
        t.visualizar_ProductoVO(tabla);
        activa_boton(true,false,false);
        limpiarCajas();
       
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txt_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_usuarioActionPerformed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        vista.inicio form=new inicio();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre_usuario;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
